/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Insights {
  createdAt: number;
  documentId: string;
  summary: string;
  updatedAt: number;
}

export interface DB {
  insights: Insights;
}
